### ISSUE TITLE
Add JDK/JVM options for reliability and stability

### ISSUE THREAD

**Issue by hrishin** [fabric8io-images/README#3]
Its observed that following JVM options from OpenShift JDK image increases application/pods reliability and stability. 
Adding following JDK/JVM options to all( or specific) java images by default could provide better developer experience

```
-XX:+UseParallelGC 
-XX:MinHeapFreeRatio=20 
-XX:MaxHeapFreeRatio=40 
-XX:GCTimeRatio=4 
-XX:AdaptiveSizePolicyWeight=90 
-XX:MaxMetaspaceSize=100m 
-XX:+ExitOnOutOfMemoryError
```

**Comment by rhuss** [comment]
Thanks ! We should indeed align our options with the options from the other images

> -XX:MaxMetaspaceSize=100m

I wonder whether we really can add a fixed size here, as it, of course, depends on the image we are running in. If not specified by the user, we calculated memory options based on the memory limits imposed on the container.

**Comment by kameshsampath** [comment]
> I wonder whether we really can add a fixed size here, as it, of course, depends on the image we are running in

@rhuss  what you mean here ?? can you please add some details ?

**Comment by kameshsampath** [comment]
@rhuss 
also adding one more thing if the experimental options for Docker Java things are added we should avoid computing from our scripts.. wdyt ?

**Comment by rhuss** [comment]
> @rhuss what you mean here ?? can you please add some details ?

This is a base image. Setting some limits to a fixed value of 100 MB seems wrong to me, as their as the limit depends on the application which is running on this image and which is not known upfront. A relative size based on the container limits given makes more sense as this limit is set by the user who knows the requirements of its app (and sized the limit accordingly).

**Comment by hrishin** [comment]
@rhuss @kameshsampath 

We did basic observation with these options. Its good to see a significant change with memory consumption with these options.
Only thing is we are dropping `-XX:MaxMetaspaceSize=100m ` option.
As it imposes the memory limit for class metadata section. TL;DR; This flag will vary from one java application to other.
WDYT?

**Comment by rhuss** [comment]
I'm happy with the relative values, and as they result from some real-world experiences I'm fine with them.
